# Generated by Django 2.2.2 on 2022-02-13 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='年齢')),
                ('gender', models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('address', models.CharField(max_length=150, verbose_name='住所')),
                ('carry_address', models.CharField(max_length=150, verbose_name='送り先住所')),
                ('is_carryed', models.BooleanField(default=False, verbose_name='送迎中判定')),
                ('facility_id', models.IntegerField(blank=True, null=True)),
                ('map_id', models.IntegerField(blank=True, null=True)),
                ('img_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='パスワード')),
            ],
            options={
                'verbose_name': '利用者',
            },
        ),
    ]
