# Generated by Django 2.2.2 on 2022-02-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='map_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.Routing'),
        ),
    ]
