# Generated by Django 2.2.2 on 2022-02-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_user_map_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='map_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.Routing'),
        ),
    ]
