# Generated by Django 2.2.2 on 2022-01-18 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220117_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)], verbose_name='住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='carry_address',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)], verbose_name='送り先住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=3, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='年齢'),
        ),
    ]
