# Generated by Django 2.2.2 on 2022-01-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220118_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=150, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='carry_address',
            field=models.CharField(max_length=150, verbose_name='送り先住所'),
        ),
    ]
