# Generated by Django 2.2.2 on 2022-01-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_carryed',
            field=models.BooleanField(default=False, verbose_name='送迎中判定'),
        ),
    ]
