# Generated by Django 2.2.2 on 2022-01-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_user_is_carryed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別'),
        ),
    ]
