# Generated by Django 2.2.2 on 2022-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220124_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
