# Generated by Django 2.2.2 on 2022-01-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_user_facility_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '利用者'},
        ),
    ]
