# Generated by Django 2.2.2 on 2022-01-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facility_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
