# Generated by Django 2.2.2 on 2022-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20220129_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='map_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
