# Generated by Django 2.2.2 on 2022-02-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_user_map_id'),
        ('customer', '0010_auto_20220130_2005'),
    ]

    operations = [
    ]
