# Generated by Django 2.2.2 on 2022-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_user_map_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
