# Generated by Django 2.2.2 on 2022-02-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_merge_20220201_0157'),
        ('customer', '0012_merge_20220201_0055'),
    ]

    operations = [
    ]
