# Generated by Django 2.2.2 on 2022-02-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_user_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
