# Generated by Django 2.2.2 on 2022-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200, verbose_name='施設前')),
                ('address', models.CharField(max_length=150, verbose_name='施設住所')),
                ('password', models.CharField(max_length=32, verbose_name='パスワード')),
            ],
        ),
    ]
