# Generated by Django 2.2.2 on 2022-01-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityuser',
            name='facility_name',
            field=models.CharField(max_length=200, verbose_name='施設名'),
        ),
    ]
