# Generated by Django 2.2.2 on 2022-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default=0, max_length=150, verbose_name='施設住所'),
        ),
    ]
