# Generated by Django 2.2.2 on 2022-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('waypoints', models.CharField(max_length=255)),
                ('facility_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Routing',
            },
        ),
    ]
