# Generated by Django 2.2.2 on 2022-02-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('waypoints', models.CharField(max_length=255)),
                ('facility_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.User')),
            ],
            options={
                'verbose_name_plural': 'Routing',
            },
        ),
    ]
