# Generated by Django 2.2.2 on 2021-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Root',
            },
        ),
    ]
