# Generated by Django 2.2.2 on 2021-11-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20211116_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
