# Generated by Django 2.2.2 on 2021-11-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20211116_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='password',
        ),
    ]
