# Generated by Django 2.2.2 on 2021-11-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_root_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Facility',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Facility')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.DeleteModel(
            name='Root',
        ),
    ]
