# Generated by Django 2.2.2 on 2021-11-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20211118_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
